final List pizzaRedBase = [
  {
    'itemId': 0,
    'currentType': 'Tomatoes',
    'name': 'Serrano Pizza',
    'ingredients': 'Tomatoes, Cheese, Serrano Ham',
    'price': '\$15',
    'image': 'images/pizza_jambonSerrano.png',
    'value': 15,
  },
  {
    'itemId': 1,
    'currentType': 'Tomatoes',
    'name': 'Pepper Pizza',
    'ingredients': 'Tomatoes, Cheese, Peppers, Olive',
    'price': '\$15',
    'image': 'images/NEWpizza_veggie.png',
    'value': 15,
  },
  {
    'itemId': 2,
    'currentType': 'Tomatoes',
    'name': 'Veggie Pizza',
    'ingredients': 'Tomatoes, Cheese, Vegetables',
    'price': '\$15',
    'image': 'images/NEWpizza_veggie2.png',
    'value': 15,
  },
  {
    'itemId': 3,
    'currentType': 'Tomatoes',
    'name': 'Pinneaple Pizza',
    'ingredients': 'Tomatoes, Cheese, Pinneaple, Ham',
    'price': '\$15',
    'image': 'images/pizza_jambon_ananas.png',
    'value': 15,
  },
  {
    'itemId': 4,
    'currentType': 'Tomatoes',
    'name': 'Basilic Pizza',
    'ingredients': 'Tomatoes, Cheese, Olive, Basilic',
    'price': '\$15',
    'image': 'images/NEWpizza_basilic.png',
    'value': 15,
  },
  {
    'itemId': 5,
    'currentType': 'Tomatoes',
    'name': 'Curry Pizza',
    'ingredients': 'Tomatoes, Cheese, Chicken, Pepper, Curry',
    'price': '\$15',
    'image': 'images/pizza_curry.png',
    'value': 15,
  },
  {
    'itemId': 6,
    'currentType': 'Tomatoes',
    'name': 'Regina Pizza',
    'ingredients': 'Tomatoes, Cheese, Ham, Mushrooms',
    'price': '\$10',
    'image': 'images/pizza_reine.png',
    'value': 10,
  },
];

final List pizzaWhiteBase = [
  {
    'itemId': 0,
    'currentType': 'Cream',
    'name': 'Kebab Pizza',
    'ingredients': 'Cream, Cheese, Kebab',
    'price': '\$15',
    'image': 'images/pizza_kebab.png',
    'value': 15,
  },
  {
    'itemId': 1,
    'currentType': 'Cream',
    'name': 'Savoyard Pizza',
    'ingredients': 'Cream, Cheese, Reblochon, Potatoes',
    'price': '\$20',
    'image': 'images/pizza_savoyarde.png',
    'value': 20,
  },
  {
    'itemId': 2,
    'currentType': 'Cream',
    'name': 'Tartiflette Pizza',
    'ingredients': 'Cream, Cheese, Tartiflette, Ham',
    'price': '\$20',
    'image': 'images/pizza_tartiflette.png',
    'value': 20,
  },
  {
    'itemId': 3,
    'currentType': 'Cream',
    'name': 'Goat Pizza',
    'ingredients': 'Cream, Cheese, Goat, Arugula',
    'price': '\$15',
    'image': 'images/pizza_chevre.png',
    'value': 15,
  },
  {
    'itemId': 4,
    'currentType': 'Cream',
    'name': 'Mussels Pizza',
    'ingredients': 'Cream, Cheese, Pepper, Mussels',
    'price': '\$20',
    'image': 'images/pizza_moules.png',
    'value': 20,
  },
];
